server:
  port: 8081

spring:
  application:
    name: ems-processor-app
  datasource:
    url: jdbc:postgresql://localhost:5432/ems_app
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  activemq:
    broker-url: tcp://localhost:61616
  jms:
    template:
      default-destination: myDefaultQueue

twilio:
  account:
    sid: ACa6f9b0890a5fca44de9b1f11ca7c3b2b
  auth:
    token: db2af8b842233a0f59843b5f17cbf8df
  phone:
    number: +16203901709