server:
  port: 30002
logging:
  level:
    root: error
    org.springframework: info
    org.springframework.security: trace
springdoc:
  show-actuator: true
management:
  endpoint:
    health:
      show-details: always
      show-components: always
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: changeit
#    key-password: changeit
##    client-auth: need
#    trust-store: classpath:truststore.p12
#    trust-store-password: changeit
spring:
  application:
  datasource:
    url: jdbc:postgresql://localhost:5432/canada_active_life
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: admin
      roles: USER, ADMIN
