server:
  port: 40002
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-password: changeit
    client-auth: need
    trust-store: classpath:truststore.p12
    trust-store-password: changeit
spring:
  application:
  datasource:
    url: jdbc:postgresql://localhost:5432/canada_active_life
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: admin
      roles: USER, ADMIN
