persistence.technology=hibernate
#persistence.technology=jdbc
#messaging.technology=rabbitmq
messaging.technology=kafka
test.mode=false
dataFileName=/Users/Akshat.Singla/Downloads/code/practice-problems/student-codebase/aksi-bootcamp-2024/pipeline-multithreaded-trade-processing/trade-producer-app/src/main/resources/trades.csv
trade.processor.queue.count=3
#trade.distribution.criteria=accountNumber
trade.distribution.criteria=tradeID
distributionLogic.useMap=true
distributionLogic.algorithm=random
db.url=jdbc:mysql://localhost:3306/hibernate_trade_processor
db.username=root
db.password=password123
db.hibernate.driver.class=com.mysql.cj.jdbc.Driver
db.hibernate.mode=update
db.hibernate.dialect=org.hibernate.dialect.MySQLDialect
rabbitMQ.hostName=localhost
rabbitMQ.guest=guest
rabbitMQ.pass=guest
rabbitMQ.main.exchange.name=credit_card_transactions




