persistence.technology=hibernate
#persistence.technology=jdbc
messaging.technology=rabbitmq
test.mode=false
chunkSize=1000
chunkPath=src/main/resources/data
dataFileName=trades.csv
trade.processor.queue.count=3
thread.pool.size.chunk.processor=10
#trade.distribution.criteria=accountNumber
trade.distribution.criteria=tradeID
distributionLogic.useMap=true
distributionLogic.algorithm=random
db.url=jdbc:mysql://localhost:3306/hibernate_trade_processor
db.username=root
db.password=password123
rabbitMQ.hostName=localhost
rabbitMQ.guest=guest
rabbitMQ.pass=guest
rabbitMQ.main.exchange.name=credit_card_transactions




