persistence.technology=hibernate
#persistence.technology=jdbc
messaging.technology=rabbitmq
test.mode=true
db.url=jdbc:mysql://localhost:3306/hibernate_trade_processor
db.username=root
db.password=password123
trade.processor.provider.count=3
thread.pool.size.trade.processor=3
rabbitMQ.hostName=localhost
rabbitMQ.guest=guest
rabbitMQ.pass=guest
rabbitMQ.main.exchange.name=credit_card_transactions
rabbitMQ.main.queue0.name=cc_partition_0_queue
rabbitMQ.main.queue0.routingKey=cc_partition_0
rabbitMQ.main.queue1.name=cc_partition_1_queue
rabbitMQ.main.queue1.routingKey=cc_partition_1
rabbitMQ.main.queue2.name=cc_partition_2_queue
rabbitMQ.main.queue2.routingKey=cc_partition_2
retry.count=3
rabbitMQ.retry.exchange.name=retry_exchange
rabbitMQ.dlx.exchange.name=dlx_exchange
rabbitMQ.dlx.queue.name=dlx_queue
rabbitMQ.dlx.routingKey=dlx_routing_key


