persistence.technology=hibernate
#persistence.technology=jdbc
messaging.technology=rabbitmq
errorLoggerFilePath=src/main/resources/error.txt
db.port.num=3306
db.username=root
db.password=password123
db.name=hibernate_trade_processor
trade.processor.queue.count=3
thread.pool.size.trade.processor=3
rabbitMQ.hostName=localhost
rabbitMQ.guest=guest
rabbitMQ.pass=guest
rabbitMQ.main.exchange.name=credit_card_transactions
rabbitMQ.main.queue.name=cc_partition_2_queue
rabbitMQ.main.routingKey=cc_partition_2
retry.count=3
rabbitMQ.retry.exchange.name=retry_exchange
rabbitMQ.dlx.exchange.name=dlx_exchange
rabbitMQ.dlx.queue.name=dlx_queue
rabbitMQ.dlx.routingKey=dlx_routing_key


