server:
  port: 8080

spring:
  application:
    name: ems
  datasource:
    url: jdbc:postgresql://localhost:5432/ems_app
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  activemq:
    broker-url: tcp://localhost:61616
  jms:
    template:
      default-destination: myDefaultQueue