server:
  port: 8082
  ssl:
    client-auth: need
    key-store: classpath:ems-keystore.p12
    key-store-password: changeit
    key-password: changeit
    trust-store: classpath:ems-truststore.p12
    trust-store-password: changeit
management:
  endpoint:
    health:
      show-details: always
      show-components: always

spring:
  application:
    name: ems
    otp:
      timeout-min: 2
      verification-timeout-min: 5
      failure:
        max-count: 3
        block-timeout-hr: 2
      generation:
        max-count: 5
        block-timeout-hr: 8
  datasource:
    url: jdbc:postgresql://localhost:5432/ems_app
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  activemq:
    broker-url: tcp://localhost:61616
  jms:
    template:
      default-destination: myDefaultQueue
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev-88265011.okta.com/oauth2/ausnnzmg69q4BhhPY5d7/v1/keys