package org.reactivestax.canada_active_life.rest_assured;

import io.restassured.RestAssured;
import io.restassured.response.Response;
import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.*;
import org.reactivestax.canada_active_life.TestDataProvider.FamilyManagementTestDataProvider;
import org.reactivestax.canada_active_life.domain.PendingSignUpUUID;
import org.reactivestax.canada_active_life.dto.FamilyMemberDTO;
import org.reactivestax.canada_active_life.dto.UserLoginDTO;
import org.reactivestax.canada_active_life.dto.UserVerificationDTO;
import org.reactivestax.canada_active_life.repo.PendingSignUpUUIDRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.web.client.RestTemplate;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.UUID;

import static io.restassured.RestAssured.given;
import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.when;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
@Slf4j
class FamilyManagementTest {

    @LocalServerPort
    private int port;

    private String baseUrl;

    @MockitoBean
    private RestTemplate restTemplate;

    @Autowired
    private DataSource dataSource;

    @Autowired
    private PendingSignUpUUIDRepository pendingSignUpUUIDRepository;

    private String actorMemberLoginId;
    private String addedMemberLoginId;
    private UUID loginUUIDToken;

    @BeforeEach
    void setUp(){
        RestAssured.baseURI = "http://localhost:";
        RestAssured.port = port;
        baseUrl = "http://localhost:"+port+"/CanadaActiveLife/v1";

        ResponseEntity<String> mockResponse = new ResponseEntity<>("Message Sent Via SMS.", HttpStatus.OK);
        when(restTemplate.postForEntity(any(String.class), any(HttpEntity.class), eq(String.class))).thenReturn(mockResponse);
    }

    @BeforeAll
    void cleanUpAutoGeneratedId() throws SQLException {
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {

            String truncate = "truncate table family_member cascade";
            stmt.execute(truncate);
            String sql = "ALTER TABLE family_member ALTER COLUMN family_member_id RESTART WITH 1";
            stmt.execute(sql);
        }
    }

    @Test
    @Order(1)
    void signUpTest(){
        FamilyMemberDTO familyMemberDTO = FamilyManagementTestDataProvider.goodFamilyMemberDTO.get();

        // Call SignUp
        Response response = given()
                .log().all() // Log request details
                .contentType("application/json")
                .body(familyMemberDTO)
                .when()
                .post(baseUrl + "/signup")
                .then()
                .statusCode(200)
                .extract()
                .response();

        String verificationMessage = response.asString();
        assertFalse(verificationMessage.isEmpty());
        assertThat(verificationMessage).isEqualTo("Family Member created. Please click on the Activation Link in the email to activate the account.");
    }

    @Test
    @Order(2)
    void activateFamilyMemberTest() {
        // Get UUID from the Repo
        PendingSignUpUUID pendingSignUpUUID = pendingSignUpUUIDRepository.findTopByFamilyMember_FamilyMemberIdOrderByCreationTimeStampDesc(1)
                .orElseThrow(RuntimeException::new);

        actorMemberLoginId = pendingSignUpUUID.getFamilyMember().getMemberLoginId();

        Response responseAddMember = given()
                .log().all() // Log request details
                .contentType("application/json")
                .queryParam("familyMemberId", "1")
                .queryParam("uuid", pendingSignUpUUID.getUuid())
                .when()
                .get(baseUrl + "/activate-account")
                .then()
                .statusCode(200)
                .extract()
                .response();

        String responseString = responseAddMember.asString();
        assertThat(responseString).isNotNull();
        assertEquals("Family Member activated.", responseString);
    }

    @Test
    @Order(3)
    void addMemberToGroupTest() {
        FamilyMemberDTO familyMemberDTO = FamilyManagementTestDataProvider.goodFamilyMemberDTO.get();

        Response response = given()
                .log().all() // Log request details
                .contentType("application/json")
                .body(familyMemberDTO)
                .header("x-security-header", actorMemberLoginId)
                .when()
                .post(baseUrl + "/members")
                .then()
                .statusCode(200)
                .extract()
                .response();

        String verificationMessage = response.asString();
        assertFalse(verificationMessage.isEmpty());
        assertThat(verificationMessage).isEqualTo("Family Member added to group.");

    }

    @Test
    @Order(4)
    void activateAddedFamilyMemberTest() {
        PendingSignUpUUID pendingSignUpUUID = pendingSignUpUUIDRepository.findTopByFamilyMember_FamilyMemberIdOrderByCreationTimeStampDesc(2)
                .orElseThrow(RuntimeException::new);

        addedMemberLoginId = pendingSignUpUUID.getFamilyMember().getMemberLoginId();

        Response responseAddMember = given()
                .log().all() // Log request details
                .contentType("application/json")
                .queryParam("familyMemberId", "2")
                .queryParam("uuid", pendingSignUpUUID.getUuid())
                .when()
                .get(baseUrl + "/activate-account")
                .then()
                .statusCode(200)
                .extract()
                .response();

        String responseString = responseAddMember.asString();
        assertThat(responseString).isNotNull();
        assertEquals("Family Member activated.", responseString);
    }

    @Test
    @Order(5)
    void getMemberTest(){
        Response response = given()
                .log().all() // Log request details
                .contentType("application/json")
                .queryParam("memberLoginId", addedMemberLoginId)
                .when()
                .get(baseUrl + "/members")
                .then()
                .statusCode(200)
                .extract()
                .response();

        FamilyMemberDTO familyMemberDTO = response.as(FamilyMemberDTO.class);
        assertThat(familyMemberDTO).isNotNull();
        assertEquals("Jane Doe", familyMemberDTO.getName());
    }

    @Test
    @Order(6)
    void updateFamilyMemberTest() {
        FamilyMemberDTO familyMemberDTO = FamilyManagementTestDataProvider.goodFamilyMemberDTOForPatch.get();

        Response response = given()
                .log().all() // Log request details
                .contentType("application/json")
                .body(familyMemberDTO)
                .queryParam("memberLoginId", addedMemberLoginId)
                .when()
                .patch(baseUrl + "/members")
                .then()
                .statusCode(200)
                .extract()
                .response();

        FamilyMemberDTO updatedFamilyMemberDTO = response.as(FamilyMemberDTO.class);
        assertThat(updatedFamilyMemberDTO).isNotNull();
        assertEquals(familyMemberDTO.getCountry(), updatedFamilyMemberDTO.getCountry());
        assertEquals(familyMemberDTO.getProvince(), updatedFamilyMemberDTO.getProvince());

    }

    @Test
    @Order(7)
    void loginTest() {
        ResponseEntity<String> mockResponse = new ResponseEntity<>("OTP Sent Via SMS.", HttpStatus.OK);
        when(restTemplate.postForEntity(any(String.class), any(HttpEntity.class), eq(String.class))).thenReturn(mockResponse);

        UserLoginDTO userLoginDTO = FamilyManagementTestDataProvider.goodLoginDTO.get();
        userLoginDTO.setMemberLoginId(addedMemberLoginId);

        Response response = given()
                .log().all() // Log request details
                .contentType("application/json")
                .body(userLoginDTO)
                .when()
                .post(baseUrl + "/login")
                .then()
                .statusCode(200)
                .extract()
                .response();

        UUID uuid = response.as(UUID.class);
        loginUUIDToken = uuid;

        assertThat(uuid).isNotNull();
    }

    @Test
    @Order(8)
    void loginVerificationTest() {
        ResponseEntity<String> mockResponse = new ResponseEntity<>("Customer Verified", HttpStatus.OK);
        when(restTemplate.postForEntity(any(String.class), any(HttpEntity.class), eq(String.class))).thenReturn(mockResponse);

        UserVerificationDTO userVerificationDTO = FamilyManagementTestDataProvider.goodLoginVerificationDTO.get();

        Response loginVerificationResponse = given()
                .log().all() // Log request details
                .contentType("application/json")
                .body(userVerificationDTO)
                .header("x-security-header", loginUUIDToken.toString())
                .when()
                .post(baseUrl + "/login/2fa")
                .then()
                .statusCode(200)
                .extract()
                .response();

        String responseString = loginVerificationResponse.asString();
        assertThat(responseString).isNotNull();
        assertEquals("Member Verified :-)", responseString);
    }

    @Test
    @Order(9)
    void deactivateFamilyMemberTest(){
        Response response = given()
                .log().all() // Log request details
                .contentType("application/json")
                .queryParam("memberLoginId", addedMemberLoginId)
                .header("x-security-header", actorMemberLoginId)
                .when()
                .delete(baseUrl + "/members")
                .then()
                .statusCode(200)
                .extract()
                .response();

        String responseString = response.asString();
        assertThat(responseString).isNotNull();
        assertEquals("Family Member Deactivated", responseString);
    }
}
