package org.reactivestax.canada_active_life.rest_assured;

import io.restassured.RestAssured;
import io.restassured.response.Response;
import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.*;
import org.reactivestax.canada_active_life.TestDataProvider.OfferedCourseTestDataProvider;
import org.reactivestax.canada_active_life.dto.OfferedCourseDTO;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;

import javax.sql.DataSource;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import static io.restassured.RestAssured.given;
import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
@Slf4j
class OfferedCourseTest {

    @LocalServerPort
    private int port;

    private String baseUrl;

    @Autowired
    private DataSource dataSource;

    @BeforeEach
    void setUp(){
        RestAssured.baseURI = "http://localhost:";
        RestAssured.port = port;
        baseUrl = "http://localhost:"+port+"/CanadaActiveLife/v1/offeredCourses";
    }

//    @BeforeAll
    void cleanUpAutoGeneratedId() throws SQLException {
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {

            String truncate = "truncate table offered_course cascade";
            stmt.execute(truncate);
            String sql = "ALTER TABLE offered_course ALTER COLUMN offered_course_id RESTART WITH 1";
            stmt.execute(sql);
        }
    }

    @Test
    @Order(1)
    void createOfferedCourseTest(){
        OfferedCourseDTO offeredCourseDTO = OfferedCourseTestDataProvider.goodOfferedCourseDTO.get();

        Response response = given()
                .log().all() // Log request details
                .contentType("application/json")
                .body(offeredCourseDTO)
                .when()
                .post(baseUrl)
                .then()
                .statusCode(200)
                .extract()
                .response();

        String verificationMessage = response.asString();
        assertFalse(verificationMessage.isEmpty());
        assertThat(verificationMessage).isEqualTo("Offered Course created.");
    }

    @Test
    @Order(2)
    void getOfferedCourseTest(){
        Response response = given()
                .log().all() // Log request details
                .contentType("application/json")
                .queryParam("offeredCourseId", "1")
                .when()
                .get(baseUrl)
                .then()
                .statusCode(200)
                .extract()
                .response();

        OfferedCourseDTO offeredCourseDTO = response.as(OfferedCourseDTO.class);
        assertThat(offeredCourseDTO).isNotNull();
        assertEquals(10, offeredCourseDTO.getNumOfClassesOffered());
        assertEquals(25, offeredCourseDTO.getSeatsAvailable());
        assertFalse(offeredCourseDTO.isAllDayCourse());
    }

    @Test
    @Order(4)
    void cancelOfferedCourseTest(){
        Response response = given()
                .log().all() // Log request details
                .contentType("application/json")
                .queryParam("offeredCourseId", "1")
                .when()
                .delete(baseUrl)
                .then()
                .statusCode(200)
                .extract()
                .response();

        String responseString = response.asString();
        assertThat(responseString).isNotNull();
        assertEquals("OfferedCourse no more available!", responseString);
    }

    @Test
    @Order(3)
    void updateOfferedCourseTest() {
        /* TODO
        FamilyMemberDTO familyMemberDTO = FamilyManagementTestDataProvider.goodFamilyMemberDTOForPatch.get();

        Response response = given()
                .log().all() // Log request details
                .contentType("application/json")
                .body(familyMemberDTO)
                .queryParam("memberLoginId", "12122")
                .when()
                .patch(BASE_URL)
                .then()
                .statusCode(200)
                .extract()
                .response();

        FamilyMemberDTO updatedFamilyMemberDTO = response.as(FamilyMemberDTO.class);
        assertThat(updatedFamilyMemberDTO).isNotNull();
        assertEquals(familyMemberDTO.getCountry(), updatedFamilyMemberDTO.getCountry());
        assertEquals(familyMemberDTO.getProvince(), updatedFamilyMemberDTO.getProvince());

         */

    }
}

